# This is a basic workflow to help you get started with Actions

name: CI

env:
  aliyun_host: 39.108.94.150
  aliyun_user: root
  target_dir: /root/incomplete-projects
  macbook_private_key: ${{ secrets.MACBOOK_PRO_PRIVATE_KEY }}

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: deploy
        run: |
          echo "${{ env.macbook_private_key }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{env.aliyun_user}}@${{env.aliyun_host}} "
            cd ${{env.target_dir}} && git fetch --all && git reset --hard origin/master &&
            cd incomplete_projects && sudo docker build -t incomplete-projects:latest . && sudo docker run -d --name incomplete_projects incomplete-projects -p 1236:1236"
